### ISSUE TITLE
Mozilla examples videos are missing on demo

### ISSUE THREAD

**Issue by alexislefebvre** [marcop135/bullframe.css#22]
**Describe the bug**
Mozilla examples videos are missing on demo

**To Reproduce**
1. Go to https://marcop135.github.io/bullframe.css/#embedded-content
2. Scroll down to _HTML5 video with controls_
4. Try to play video

**Expected behavior**
See a video

**Screenshots**
> ![image](https://user-images.githubusercontent.com/2071331/102545389-77056580-40b6-11eb-801b-1385e6b12872.png)

**Desktop and Smartphone:**
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
Missing files:
- https://interactive-examples.mdn.mozilla.net/media/examples/flower.webm
- https://interactive-examples.mdn.mozilla.net/media/examples/flower.mp4

**Comment by marcop135** [comment]
@alexislefebvre you are right, thanks 👍🏼! It looks like that Mozilla changed the video source paths on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video). 
Fixed 8e407dd88bc0154dbb7520caa28b1594b288effb
It will be merged soon in [v3.4.0](https://github.com/marcop135/bullframe.css/tree/v3.4.0)
